### ISSUE TITLE
Problems with logs

### ISSUE THREAD

**Issue by Marfeld** [schwarper/cs2-parachute#2]
A few days ago I had a problem where my logs were 4GB in size. And this message was constantly being written in the logs. Could this be caused by the CS2 Parachute plugin?

```
2024-09-18 01:45:23.492 +00:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Schema target points to null. (Parameter 'pointer')
   at CounterStrikeSharp.API.Modules.Memory.Schema.GetDeclaredClass[T](IntPtr pointer, String className, String memberName) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/Schema.cs:line 101
   at Parachute.Parachute.OnTick() in C:\Users\mervt\OneDrive\Masaüstü\cs\New folder\cs2-parachute\src\cs2-parachute.cs:line 71
   at InvokeStub_OnTick.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.BasePlugin.<>c__DisplayClass51_0`1.<RegisterListener>b__2(ScriptContext context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 297
   at InvokeStub_Action`1.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context)
```

Greetings Mafel

**Comment by schwarper** [comment]
https://github.com/schwarper/cs2-parachute/commit/36a7120adca0715e78541a7ac0c5de23ffcc485e
